# Generated by Django 4.0.2 on 2022-03-15 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 15, 18, 47, 30, 405038)),
            preserve_default=False,
        ),
    ]
