# Generated by Django 4.0.2 on 2022-03-16 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_metrics_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 14, 20, 20, 556564, tzinfo=utc)),
        ),
    ]
